drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text,
    url text not null,
    description text,
    rating integer not null
);

insert into bookmarks (title, url, description, rating)
values
    ('google', 'https://www.google.com', 'search engine', 1),
    ('yahoo', 'https://www.yahoo.com', 'search engine', 2),
    ('yelp', 'https://www.yelp.com', 'review site', 3),
    ('espn', 'https://www.espn.com', 'sports', 2),
    ('nfl', 'https://www.nfl.com', 'football', 3),
    ('nba', 'https://www.nba.com', 'basketball', 4),
    ('netflix', 'https://www.netflix.com', 'entertainment', 5),
    ('youtube', 'https://www.youtube.com', 'entertainment', 4),
    ('github', 'https://www.github.com', 'repository site', 2),
    ('twitch', 'https://www.twitch.tv', 'entertainment', 2);